name: lovable

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: lovable-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    # restart: always
    volumes:
      - lovable-zookeeper-data:/var/lib/zookeeper/data
      - lovable-zookeeper-log:/var/lib/zookeeper/log

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: lovable-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    depends_on:
      - zookeeper
    # restart: always
    volumes:
      - lovable-kafka-data:/var/lib/kafka/data

volumes:
  lovable-kafka-data:
    driver: local
  lovable-zookeeper-data:
    driver: local
  lovable-zookeeper-log:
    driver: local
