services:
  control:
    build:
      context: .
      dockerfile: ./runable/apps/control/Dockerfile
      platforms:
        - linux/amd64
    image: elbavol-control:latest
    container_name: elbavol-control

  serve:
    build:
      context: .
      dockerfile: ./runable/apps/serve/Dockerfile
      platforms:
        - linux/amd64
    image: elbavol-serve:latest
    container_name: elbavol-serve

  ingress:
    build:
      context: .
      dockerfile: ./ingress/Dockerfile
      platforms:
        - linux/amd64
    image: elbavol-ingress:latest
    container_name: elbavol-ingress
    ports:
      - "8080:8080"
    environment:
      DOMAIN: localhost

  orchestrator:
    build:
      context: .
      dockerfile: ./orchestrator/Dockerfile
      platforms:
        - linux/amd64
    image: elbavol-orchestrator:latest
    container_name: elbavol-orchestrator
    ports:
      - "8081:8080"
    environment:
      KAFKA_URL: kafka:9092
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin

  prime:
    build:
      context: .
      dockerfile: ./prime/Dockerfile
      platforms:
        - linux/amd64
    image: elbavol-prime:latest
    container_name: elbavol-prime
    ports:
      - "8082:8080"
    environment:
      KAFKA_URL: kafka:9092
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin

  minio:
    image: minio/minio:latest
    container_name: elbavol-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-data:/data
    command: server /data --console-address :9001

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: elbavol-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    # restart: always
    volumes:
      - elbavol-zookeeper-data:/var/lib/zookeeper/data
      - elbavol-zookeeper-log:/var/lib/zookeeper/log

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: elbavol-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    # restart: always
    volumes:
      - elbavol-kafka-data:/var/lib/kafka/data

volumes:
  minio-data:
    driver: local
  elbavol-kafka-data:
    driver: local
  elbavol-zookeeper-data:
    driver: local
  elbavol-zookeeper-log:
    driver: local
