name: Build and Push Docker Images

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    name: Build and Push Docker images to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Ingress Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./ingress/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/elbavol-ingress:latest

      - name: Build and Push Orchestrator Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./orchestrator/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/elbavol-orchestrator:latest

      - name: Build and Push Prime Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./prime/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/elbavol-prime:latest

      - name: Build and Push Control Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./runable/apps/control/dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/elbavol-control:latest

      - name: Build and Push Serve Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./runable/apps/serve/dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/elbavol-serve:latest
